### ISSUE TITLE
wrong "build failed" message in intro to SPARK 

### ISSUE THREAD

**Issue by yannickmoy** [AdaCore/learn#251]
The last widget in the intro to SPARK section "Debugging Errors in Code or Specification" in chapter 3 on Proof of Program Integrity is failing with the following message when hitting the Run button:

Console Output:
$ gprbuild -q -P main -gnatwa
Build failed...

There is no reason for that. I tried locally with Community 2019 and the code compiles correctly, and should fail only an assertion at runtime.

**Comment by Robert-Tice** [comment]
This is because the code for the lab is incorrectly indented. There is an extra space added before the line ` procedure Main is` which messed up the regex which validates that there is a valid main present. 

@setton The current regex is `^procedure +[A-Za-z][_a-zA-Z0-9]*[ |\n]+(is|with)`. Since it is valid Ada code to add spaces before the `procedure` keyword, I think we should reconsider this regex to be something like: `^ *procedure +[A-Za-z][_a-zA-Z0-9]*[ |\n]+(is|with)`. What do you think?

**Comment by yannickmoy** [comment]
argh. I need to add one space before :class: line, so that this aligns with the code that follows. I'll do under another cleanup commit in progress. I let you decide if you want to change the regexp, as this is something we already stumbled upon.

**Comment by Robert-Tice** [comment]
Fixed in PR #274
