### ISSUE TITLE
PDF download of "Intro to Ada" issues.

### ISSUE THREAD

**Issue by DelusionalMuppet** [AdaCore/learn#506]
The PDF generated by PDF download button in the index page of introduction to Ada course has the following issues:
1. Code examples do not list the code file name. Hence it is difficult to know if it is an adb or ads file extensions.
2. In the tabbed code examples, PDF file generated do not print out all the tabs, just the codes on the first tab.

On the webpages, some code examples lacked the download button. Also some codes are downloaded in a zip files (which is greatly appreciated since it contains all the code examples listed in the bundle) while some download in individual files (download only the code shown in the active tab).

Other than that the introduction course is very helpful for a beginner like me.

For the online lab issues, if you write the code on the online editor:
1. Hello world expect an index or integer input which is not stated in the problem statement. Doing it on and compiling on an offline editor or GNAT is straightforward, but not on the online editor.
2. Second problem, Greet, for a complete beginner stating the function Greet like that is a bit confusing. Especially if we expect the statement is complete. Again, the expected integer input is not stated clearly in the problem statement. If we do the exercises on our computer we can do it relatively straight forward. Not on the online editor.
3. I can't speak of the other exercises, since I gave up on the online editor and just do it on GNAT. But the experience of using the online editor just for those two beginning problem is less pleasant.
Thanks.

**Comment by Robert-Tice** [comment]
@DelusionalMuppet Thanks for your feedback! We have updated the site to include some fixes from your report. Other items from your report, we need some clarification so that we can track down the problems.

1.) The code examples in the PDF now include the file names.
2.) Can you provide a specific example where you see this happening? We have not seen this occur.

The download button issue has been fixed and deployed.

Labs:
1.) The Hello World example doesn't expect any input. You can see the solution here:
https://learn.adacore.com/labs/intro-to-ada/chapters/solutions.html#hello-world
2.) Can you provide some more detail, or a suggestion for the Greet lab? Above the code editor there is the "Requirements" section which does describe that the program expects some input string to be processed.
3.) Its possible that the "Submit" button is the confusing part here? The Submit button submits the code in the editor(s) to our servers which passes it through a series of tests. Each test has an input and an expected output. If you hit submit on a lab, you'll see the set of Test Cases that were used to judge the lab. Each test case lists the input that was used, the expected output, and the received output.

**Comment by DelusionalMuppet** [comment]
Right, thank you.
Regarding number 2, that was me earning my username. Careful reading do show the tabs are printed correctly. Sorry about that.
Regarding the lab:
It is correct that the submit button behaviour that is confusing. The programs successfully compile but then proceed to fail. Such as hello world program fail with test number 0. If the test case is important, should it not be specified on the problem statement?
That way we as a beginner also need to be aware of the test cases and what we as a beginner need to be aware of. The lab problem by itself is straight forward, although stating the string variable do throw me off a little bit.
As it is thank you for the enhancement and I consider this issue closed.
